### ISSUE TITLE
Is code in document need update？

### ISSUE THREAD

**Issue by howtoesc** [vuejs/eslint-config-prettier#13]
I use the demo code in document https://vuepress-theme-hope.github.io/v2/md-enhance/zh/guide/flowchart.html
``` ts
// .vuepress/config.ts
import { mdEnhance } from "vuepress-plugin-md-enhance";

export default {
  plugins: [
    mdEnhance({
      // 开启标记
      mark: true,
    }),
  ],
};
```
then I got erro 
```bash
~/sandbox/writing main ⇡1 +54 !44 ?22 ❯ yarn docs:build                                     4s
TypeError: (0 , import_vuepress_plugin_md_enhance.mdEnhance) is not a function
    at Object.<anonymous> (/home/howtoesc/sandbox/writing/vuepress.config.ts:78:53)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.require.extensions..ts (/home/howtoesc/sandbox/writing/node_modules/@vuepress/cli/lib/utils/allowTs.js:11:11)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadUserConfigEs (/home/howtoesc/sandbox/writing/node_modules/@vuepress/cli/lib/config/loadUserConfigEs.js:9:22)
    at loadUserConfig (/home/howtoesc/sandbox/writing/node_modules/@vuepress/cli/lib/config/loadUserConfig.js:16:20)
    at /home/howtoesc/sandbox/writing/node_modules/@vuepress/cli/lib/commands/build/createBuild.js:21:58
```

I notice that the demo code in [home page](https://vuepress-theme-hope.github.io/v2/md-enhance/zh/) is diffrent，these errors ware disappear when I changed follow it
```ts
// .vuepress/config.ts
import { mdEnhancePlugin } from "vuepress-plugin-md-enhance";

export default {
  plugins: [
    mdEnhancePlugin({
      // 你的选项
    }),
  ],
};
```

**Comment by sodatea** [comment]
This issue doesn't seem to be related to this project.
I think you might have opened the issue in the wrong repository.
